# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjhHZlSl95YvoFoCPDZYMcE6rBRq96Ez
"""

import streamlit as st
import os
import openai
from PyPDF2 import PdfReader
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.chat_models import ChatOpenAI
from langchain.chains.question_answering import load_qa_chain
from dotenv import load_dotenv

# ------------------ LOAD ENVIRONMENT VARIABLES ------------------
load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")

# ------------------ STREAMLIT APP CONFIG ------------------
st.set_page_config(page_title="📘 AI StudyMate Tool", layout="wide")
st.title("📘 AI StudyMate - Your Smart Study Assistant")
st.write("Upload PDFs and ask any questions to get instant answers!")

# ------------------ PDF UPLOAD ------------------
uploaded_files = st.file_uploader("Upload your study PDFs", type=["pdf"], accept_multiple_files=True)

if uploaded_files:
    st.success("✅ PDF uploaded successfully!")







